
RUN apt-get update && \
  apt-get install -y \
  apt-utils \
  python \
  python-apt \
  python-yaml \
  aptitude \
  sudo && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/lib/summon \
  && \
  wget -qO- https://github.com/cyberark/summon/releases/download/v0.6.5/summon-linux-amd64.tar.gz | tar xvz -C /usr/local/bin \
  && \
  wget -qO- https://github.com/cyberark/summon-conjur/releases/download/v0.3.0/summon-conjur-linux-amd64.tar.gz | tar xvz -C /usr/local/lib/summon
