FROM conjurinc/cli5

RUN apt-get update && \
  apt-get install -y \
  apt-utils \
  python \
  python-apt \
  python-yaml \
  aptitude \
  sudo && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/lib/summon \
  && \
  wget -qO- https://github.com/cyberark/summon/releases/download/v0.6.5/summon-linux-amd64.tar.gz | tar xvz -C /usr/local/bin

#summon-conjur Beta version
COPY conjur-client-files/summon-conjur /usr/local/lib/summon/

